# Generated by Django 6.1 on 2026-08-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('reservation', 'Table Reservation'), ('catering', 'Catering Inquiry'), ('feedback', 'Feedback/Suggestion'), ('complaint', 'Complaint'), ('partnership', 'Business Partnership'), ('other', 'Other')], max_length=200)),
                ('message', models.TextField()),
                ('newsletter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
