# Generated by Django 6.1 on 2026-08-18 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday Party', 'Birthday Party'), ('Corporate Event', 'Corporate Event'), ('Family Gathering', 'Family Gathering'), ('Other Celebration', 'Other Celebration')], max_length=100)),
                ('guests_range', models.CharField(choices=[('20-50', '20-50 People'), ('51-100', '51-100 People'), ('101-200', '101-200 People'), ('201-500', '201-500 People'), ('500+', '500+ People')], max_length=100)),
                ('event_date', models.DateField()),
                ('preferred_package', models.CharField(choices=[('Basic', 'Basic (रु 500/person)'), ('Premium', 'Premium (रु 800/person)'), ('Custom', 'Custom (Contact for Quote)')], max_length=100)),
                ('additional_requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateDiningBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('12:00 PM - 4:00 PM', '12:00 PM - 4:00 PM'), ('5:00 PM - 9:00 PM', '5:00 PM - 9:00 PM'), ('6:00 PM - 10:00 PM', '6:00 PM - 10:00 PM'), ('7:00 PM - 11:00 PM', '7:00 PM - 11:00 PM')], max_length=100)),
                ('guests', models.PositiveSmallIntegerField()),
                ('occasion', models.CharField(choices=[('Business Meeting', 'Business Meeting'), ('Family Celebration', 'Family Celebration'), ('Birthday Party', 'Birthday Party'), ('Anniversary', 'Anniversary'), ('Other', 'Other')], max_length=100)),
                ('special_requests', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_type', models.CharField(choices=[('Momo Making Masterclass', 'Momo Making Masterclass'), ('Traditional Thali Workshop', 'Traditional Thali Workshop'), ('Nepali Street Food Special', 'Nepali Street Food Special'), ('Custom Group Workshop', 'Custom Group Workshop')], max_length=100)),
                ('preferred_date', models.DateField()),
                ('number_of_participants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('time_preference', models.CharField(blank=True, choices=[('10:00 AM - 1:00 PM', '10:00 AM - 1:00 PM'), ('2:00 PM - 5:00 PM', '2:00 PM - 5:00 PM'), ('6:00 PM - 9:00 PM', '6:00 PM - 9:00 PM')], max_length=30)),
                ('participant_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
